/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type WordLength = "4" | "5" | "6";

export interface AuthorizedUser {
  authorizedBy: string;
  chatId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  userId: string;
}

export interface BannedUser {
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface BroadcastChat {
  createdAt: Generated<Timestamp>;
  id: string;
  name: string | null;
  updatedAt: Generated<Timestamp>;
  username: string | null;
}

export interface ChatGameTopic {
  allowedLengths: Generated<number[]>;
  chatId: string;
  createdAt: Generated<Timestamp>;
  iconCustomEmojiId: string | null;
  name: string | null;
  shouldRecreateOnExpire: Generated<boolean>;
  topicId: string;
  updatedAt: Generated<Timestamp>;
}

export interface DailyGuess {
  attemptNumber: number;
  createdAt: Generated<Timestamp>;
  dailyWordId: number;
  guess: string;
  id: Generated<number>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface DailyWord {
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  dayNumber: Generated<number>;
  id: Generated<number>;
  meaning: string | null;
  phonetic: string | null;
  sentence: string | null;
  updatedAt: Generated<Timestamp>;
  word: string;
}

export interface Game {
  activeChat: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  startedBy: string | null;
  topicId: Generated<string>;
  updatedAt: Generated<Timestamp>;
  word: string;
}

export interface Guess {
  chatId: string;
  createdAt: Generated<Timestamp>;
  gameId: number;
  guess: string;
  id: Generated<number>;
  updatedAt: Generated<Timestamp>;
}

export interface Leaderboard {
  chatId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  score: number;
  updatedAt: Generated<Timestamp>;
  userId: string;
  wordLength: Generated<WordLength>;
}

export interface User {
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  updatedAt: Generated<Timestamp>;
  username: string | null;
}

export interface UserStat {
  createdAt: Generated<Timestamp>;
  currentStreak: Generated<number>;
  highestStreak: Generated<number>;
  lastGuessed: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface DB {
  authorizedUsers: AuthorizedUser;
  bannedUsers: BannedUser;
  broadcastChats: BroadcastChat;
  chatGameTopics: ChatGameTopic;
  dailyGuesses: DailyGuess;
  dailyWords: DailyWord;
  games: Game;
  guesses: Guess;
  leaderboard: Leaderboard;
  users: User;
  userStats: UserStat;
}
